# Generated by Django 5.2.15 on 2026-07-09 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_video', models.FileField(help_text='Original uploaded MP4', upload_to='videos/raw/')),
                ('hls_playlist', models.CharField(blank=True, help_text='Path to .m3u8 file', max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('PROCESSING', 'Processing (FFmpeg)'), ('READY', 'Ready for Streaming'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
