# Generated by Django 5.2.15 on 2026-07-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videohistory'),
    ]

    operations = [
    ]
